# Generated by Django 3.1.4 on 2020-12-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201207_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='time_stamp',
            new_name='date',
        ),
    ]
